// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbmmxMLyKSj1V00HJrS0JUVgp1g2rJH_E',
    appId: '1:579584049009:web:c00caca30b8fb3f4f840d0',
    messagingSenderId: '579584049009',
    projectId: 'sport-app-db-dec8c',
    authDomain: 'sport-app-db-dec8c.firebaseapp.com',
    storageBucket: 'sport-app-db-dec8c.firebasestorage.app',
    measurementId: 'G-PB5MNHB1HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS47m_YRyerCSD5CVRGA2KwmS1NOp2cXw',
    appId: '1:579584049009:android:19cf2b16e6123bc0f840d0',
    messagingSenderId: '579584049009',
    projectId: 'sport-app-db-dec8c',
    storageBucket: 'sport-app-db-dec8c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbmmxMLyKSj1V00HJrS0JUVgp1g2rJH_E',
    appId: '1:579584049009:web:129ad440c5ced8cbf840d0',
    messagingSenderId: '579584049009',
    projectId: 'sport-app-db-dec8c',
    authDomain: 'sport-app-db-dec8c.firebaseapp.com',
    storageBucket: 'sport-app-db-dec8c.firebasestorage.app',
    measurementId: 'G-GBHRFWWLQ9',
  );
}
